"""empty message

Revision ID: a73cdcb5ab5f
Revises: bb7c399b09e5
Create Date: 2021-10-16 23:57:57.038262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73cdcb5ab5f'
down_revision = 'bb7c399b09e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('searchCode', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flat', 'searchCode')
    # ### end Alembic commands ###
