"""flats table

Revision ID: bb7c399b09e5
Revises: 30384d6436e5
Create Date: 2021-02-20 13:53:58.395631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7c399b09e5'
down_revision = '30384d6436e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('pictureLink', sa.String(length=240), nullable=True))
    op.add_column('flatcurrent', sa.Column('pictureLink', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flatcurrent', 'pictureLink')
    op.drop_column('flat', 'pictureLink')
    # ### end Alembic commands ###
