"""flats table

Revision ID: c2b1cf3ab0cc
Revises: da41c73ee16c
Create Date: 2020-08-15 23:28:18.647334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b1cf3ab0cc'
down_revision = 'da41c73ee16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('roomsNo', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('pricePerM2', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_district'), 'flat', ['district'], unique=False)
    op.create_index(op.f('ix_flat_title'), 'flat', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_title'), table_name='flat')
    op.drop_index(op.f('ix_flat_district'), table_name='flat')
    op.drop_table('flat')
    # ### end Alembic commands ###
