"""users table

Revision ID: da41c73ee16c
Revises: 45f1b3e2aa69
Create Date: 2020-08-15 23:27:26.207973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da41c73ee16c'
down_revision = '45f1b3e2aa69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flat_district', table_name='flat')
    op.drop_index('ix_flat_title', table_name='flat')
    op.drop_table('flat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=240), nullable=True),
    sa.Column('district', sa.VARCHAR(length=64), nullable=True),
    sa.Column('roomsNo', sa.VARCHAR(length=64), nullable=True),
    sa.Column('size', sa.VARCHAR(length=64), nullable=True),
    sa.Column('price', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pricePerM2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('link', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flat_title', 'flat', ['title'], unique=False)
    op.create_index('ix_flat_district', 'flat', ['district'], unique=False)
    # ### end Alembic commands ###
